"""knowledge-worker (v1): poll-the-table ingestion worker, no message broker.

Claims the oldest queued ingestion job with SELECT ... FOR UPDATE SKIP LOCKED,
extracts structured Markdown from the stored original through the parser
preference chain (Marker -> PyMuPDF -> OCR), and writes it to
storage/parsed/<book_id>/<job_id>.md with a per-job parse log under
storage/logs/. Run with `python -m app.worker`.
"""

import time
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path

from sqlalchemy import create_engine, delete, select
from sqlalchemy.orm import Session, sessionmaker

from app.config import Settings
from app.extraction import (
    EXTRACTION_PROMPT_VERSION,
    EXTRACTION_SYSTEM_PROMPT,
    build_extraction_prompt,
    chapter_body,
    parse_extraction_response,
    resolve_source,
)
from app.llm import LLMProvider, build_llm_provider
from app.models import Book, BookProfile, Chapter, IngestionJob, KnowledgeObject, Section
from app.parsing import ParserChain, build_default_chain
from app.profile import PROFILE_PROMPT_VERSION, PROFILE_SYSTEM_PROMPT, build_profile_prompt
from app.storage import BookStorage
from app.structure import detect_structure

POLL_INTERVAL_SECONDS = 1.0

# Module-level so Marker's model load (when installed) happens once per process.
DEFAULT_CHAIN = build_default_chain()


def build_default_llm() -> LLMProvider:
    """Provider used when the caller injects none. A separate function so tests
    can substitute a stub without touching every process_one_job call site."""
    return build_llm_provider(Settings())


def _claim_next_job(session: Session) -> IngestionJob | None:
    return session.scalars(
        select(IngestionJob)
        .where(IngestionJob.status == "queued")
        .order_by(IngestionJob.created_at, IngestionJob.id)
        .limit(1)
        .with_for_update(skip_locked=True)
    ).first()


def _detect_and_replace_structure(
    session: Session, book: Book, markdown: str, log: Callable[[str], None]
) -> None:
    """Structure detection stage: replace the book's chapter/section tree."""
    log("structure: detecting chapters and sections")
    try:
        detected = detect_structure(markdown)
        session.execute(delete(Chapter).where(Chapter.book_id == book.id))
        for chapter_position, chapter in enumerate(detected):
            session.add(
                Chapter(
                    book_id=book.id,
                    position=chapter_position,
                    title=chapter.title,
                    source_line=chapter.line,
                    sections=[
                        Section(
                            position=section_position,
                            title=section.title,
                            source_line=section.line,
                        )
                        for section_position, section in enumerate(chapter.sections)
                    ],
                )
            )
        section_count = sum(len(chapter.sections) for chapter in detected)
        log(f"structure: {len(detected)} chapters, {section_count} sections")
    except Exception as exc:
        log(f"structure: failed — {type(exc).__name__}: {exc}")
        raise RuntimeError(f"structure detection stage failed: {exc}") from exc


def _generate_profile(
    session: Session, book: Book, llm: LLMProvider, log: Callable[[str], None]
) -> None:
    """Profile stage: append a new versioned profile from metadata, hints, and structure."""
    log("profile: generating book profile")
    try:
        chapters = list(
            session.scalars(
                select(Chapter).where(Chapter.book_id == book.id).order_by(Chapter.position)
            )
        )
        prompt = build_profile_prompt(book, chapters)
        response = llm.complete(prompt, system=PROFILE_SYSTEM_PROMPT)
        session.add(
            BookProfile(
                book_id=book.id,
                content=response.text,
                model=response.model,
                prompt_version=PROFILE_PROMPT_VERSION,
            )
        )
        log(f"profile: generated by {response.model} (prompt v{PROFILE_PROMPT_VERSION})")
    except Exception as exc:
        log(f"profile: failed — {type(exc).__name__}: {exc}")
        raise RuntimeError(f"profile generation stage failed: {exc}") from exc


def _extract_knowledge(
    session: Session,
    book: Book,
    markdown: str,
    llm: LLMProvider,
    log: Callable[[str], None],
) -> None:
    """Extraction stage: replace the book's knowledge objects, one LLM call per chapter."""
    log("extraction: extracting knowledge objects")
    try:
        chapters = list(
            session.scalars(
                select(Chapter).where(Chapter.book_id == book.id).order_by(Chapter.position)
            )
        )
        session.execute(delete(KnowledgeObject).where(KnowledgeObject.book_id == book.id))
        if not chapters:
            log("extraction: no chapters detected; nothing to extract")
            return
        total = 0
        for index, chapter in enumerate(chapters):
            next_chapter = chapters[index + 1] if index + 1 < len(chapters) else None
            body = chapter_body(
                markdown, chapter.source_line, next_chapter.source_line if next_chapter else None
            )
            response = llm.complete(
                build_extraction_prompt(book, chapter, body), system=EXTRACTION_SYSTEM_PROMPT
            )
            for extracted in parse_extraction_response(response.text):
                section, source_location = resolve_source(chapter, extracted.section_index)
                if extracted.section_index is not None and section is None:
                    log(
                        f"extraction: section_index {extracted.section_index} out of range "
                        f"for chapter {chapter.position + 1}; keeping chapter link only"
                    )
                session.add(
                    KnowledgeObject(
                        book_id=book.id,
                        chapter_id=chapter.id,
                        section_id=section.id if section is not None else None,
                        type=extracted.type,
                        title=extracted.title,
                        content=extracted.content,
                        summary=extracted.summary,
                        source_location=source_location,
                        confidence=extracted.confidence,
                        edition=book.edition,
                        page=extracted.page,
                        paragraph=extracted.paragraph,
                        extraction_model=response.model,
                        extraction_prompt_version=EXTRACTION_PROMPT_VERSION,
                    )
                )
                total += 1
        log(
            f"extraction: {total} knowledge objects from {len(chapters)} chapters "
            f"(prompt v{EXTRACTION_PROMPT_VERSION})"
        )
    except Exception as exc:
        log(f"extraction: failed — {type(exc).__name__}: {exc}")
        raise RuntimeError(f"knowledge extraction stage failed: {exc}") from exc


def process_one_job(
    session_factory: sessionmaker[Session],
    storage_root: Path,
    chain: ParserChain | None = None,
    llm: LLMProvider | None = None,
) -> bool:
    """Claim and run the oldest queued job. Returns whether a job was processed."""
    storage = BookStorage(storage_root)
    chain = chain or DEFAULT_CHAIN
    with session_factory() as session:
        job = _claim_next_job(session)
        if job is None:
            return False
        job.status = "running"
        job.started_at = datetime.now(UTC)
        session.commit()  # releases the claim lock; the job is now visibly running

        log_lines: list[str] = []

        def log(line: str) -> None:
            log_lines.append(f"{datetime.now(UTC).isoformat()} {line}")

        try:
            book = session.get(Book, job.book_id)
            if book is None:
                raise RuntimeError(f"Book {job.book_id} no longer exists")
            result = chain.extract(Path(book.storage_path), book.file_format, log)
            job.output_path = str(storage.save_parsed(book.id, job.id, result.markdown))
            job.parser_used = result.parser
            _detect_and_replace_structure(session, book, result.markdown, log)
            llm = llm or build_default_llm()
            _generate_profile(session, book, llm, log)
            _extract_knowledge(session, book, result.markdown, llm, log)
            job.status = "succeeded"
        except Exception as exc:
            # Discard partial stage writes (e.g. a structure delete whose
            # replacement inserts never landed) before recording the failure.
            session.rollback()
            job.status = "failed"
            job.error = f"{type(exc).__name__}: {exc}"
        job.finished_at = datetime.now(UTC)
        try:
            storage.save_log(job.id, "".join(f"{line}\n" for line in log_lines))
        except OSError:
            pass  # the parse log is diagnostics; never let it sink the run record
        session.commit()
        return True


def run_forever() -> None:
    settings = Settings()
    engine = create_engine(settings.database_url)
    session_factory = sessionmaker(bind=engine)
    llm = build_llm_provider(settings)  # fail fast on misconfiguration, build once
    while True:
        if not process_one_job(session_factory, settings.storage_root, llm=llm):
            time.sleep(POLL_INTERVAL_SECONDS)


if __name__ == "__main__":
    run_forever()
